In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans

In [1]:
from src.utils.io import load_model, read_pandas

model_path = '../../models/kmeans_50'
feature_path = '../../data/processed/feature.csv'

# load model
model = load_model(model_path)

# load feature
feature = read_pandas(feature_path)

ModuleNotFoundError: No module named 'src'

In [4]:
data = pd.read_csv(clean_data_path)
feature = pd.read_csv(feature_path)

In [5]:
feature

      engin_size  seat_num  door_num  gearbox_automatic  gearbox_manual
0      -0.775682 -2.135563 -1.731768           1.089790       -1.089790
1      -0.775682 -2.135563 -1.731768           1.089790       -1.089790
2      -0.775682 -2.135563 -1.731768           1.089790       -1.089790
3      -0.775682 -0.553133 -0.908647          -0.917608        0.917608
4      -0.775682 -0.553133 -0.908647          -0.917608        0.917608
...          ...       ...       ...                ...             ...
2863    0.065983  1.820511  0.737594           1.089790       -1.089790
2864   -0.270683  1.820511  0.737594           1.089790       -1.089790
2865    0.065983  1.820511  0.737594           1.089790       -1.089790
2866   -0.270683  1.820511  0.737594           1.089790       -1.089790
2867   -0.270683  1.820511  0.737594           1.089790       -1.089790

[2868 rows x 5 columns]

In [7]:
# fit model
kmeans = KMeans(n_clusters=50, random_state=0).fit(feature)

# predict: get cluster assignment
cluster_assignment = kmeans.predict(feature)

# append cluster assignment to data
labels = data.copy()
labels['class'] = cluster_assignment

labels

,car_id,maker,genmodel,year,bodytype,genmodel_id,engin_size,gearbox,fuel_type,price,seat_num,door_num,class
0,0,Abarth,124 Spider,2017,Convertible,2_1,1.4,Automatic,Petrol,24479.166667,2.0,2.0,12
1,1,Abarth,124 Spider,2018,Convertible,2_1,1.4,Automatic,Petrol,23656.875000,2.0,2.0,12
2,2,Abarth,124 Spider,2021,Convertible,2_1,1.4,Automatic,Petrol,20668.166667,2.0,2.0,12
3,3,Abarth,595,2016,Hatchback,2_4,1.4,Manual,Petrol,11492.500000,4.0,3.0,2
4,4,Abarth,595,2017,Hatchback,2_4,1.4,Manual,Petrol,11500.000000,4.0,3.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,2863,Volvo,XC90,2017,SUV,96_18,2.4,Automatic,Diesel,21030.437500,7.0,5.0,5
2864,2864,Volvo,XC90,2018,Estate,96_18,2.0,Automatic,Diesel,49997.750000,7.0,5.0,5
2865,2865,Volvo,XC90,2018,SUV,96_18,2.4,Automatic,Diesel,23992.653894,7.0,5.0,5
2866,2866,Volvo,XC90,2020,SUV,96_18,2.0,Automatic,Petrol Plug-in Hybrid,48663.000000,7.0,5.0,5
2867,2867,Volvo,XC90,2021,SUV,96_18,2.0,Automatic,Diesel Hybrid,46651.942857,7.0,5.0,5

In [8]:
from sklearn.metrics import silhouette_score

In [11]:
silhouette_score(feature, cluster_assignment)

0.6364271861498605

In [90]:
predictions['class'].value_counts()

4     374
19    251
7     228
25    192
24    118
29    112
1      99
30     99
10     87
42     87
5      80
22     80
2      69
3      69
15     58
35     52
11     48
21     47
34     46
12     44
8      41
26     40
45     37
17     37
31     36
37     36
13     33
44     31
38     31
18     29
33     28
39     27
0      25
9      24
16     22
47     20
46     20
20     14
14     14
48     12
41     11
6      10
28      9
27      9
23      8
49      7
43      7
36      5
40      4
32      1
Name: class, dtype: int64